# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

user = User.find_or_create_by!(email: "dokter@klinikgigi.com") do |u|
  u.password = "password123"
  u.password_confirmation = "password123"
  u.name = "Dr. Gigi"
end

treatment_catalogs = [
  { code: "GG-001", name: "Konsultasi",                   category: "Umum" },
  { code: "GG-002", name: "Cabut Gigi Anak",              category: "Bedah" },
  { code: "GG-003", name: "Cabut Gigi Dewasa",            category: "Bedah" },
  { code: "GG-004", name: "Cabut Gigi dengan Komplikasi", category: "Bedah" },
  { code: "GG-005", name: "Tambal Sementara",             category: "Konservasi" },
  { code: "GG-006", name: "Tambal Permanen (Komposit)",   category: "Konservasi" },
  { code: "GG-007", name: "Tambal Permanen (Amalgam)",    category: "Konservasi" },
  { code: "GG-008", name: "Perawatan Saluran Akar (PSA)", category: "Endodonti" },
  { code: "GG-009", name: "Scaling (Ultrasonic)",         category: "Periodonti" },
  { code: "GG-010", name: "Rontgen Periapikal",            category: "Radiologi" },
  { code: "GG-011", name: "Rontgen Panoramik",             category: "Radiologi" },
  { code: "GG-012", name: "Incisi Abses",                  category: "Bedah" }
]

treatment_catalogs.each do |tc|
  user.treatment_catalogs.find_or_create_by!(code: tc[:code]) do |t|
    t.name = tc[:name]
    t.category = tc[:category]
  end
end

icd_codes = [
  { code: "K00.0", description: "Anodontia", category: "K00" },
  { code: "K00.1", description: "Supernumerary teeth", category: "K00" },
  { code: "K00.2", description: "Abnormalities of size and form of teeth", category: "K00" },
  { code: "K00.3", description: "Mottled teeth", category: "K00" },
  { code: "K00.4", description: "Disturbances in tooth formation", category: "K00" },
  { code: "K00.5", description: "Hereditary disturbances in tooth structure", category: "K00" },
  { code: "K00.6", description: "Disturbances in tooth eruption", category: "K00" },
  { code: "K00.7", description: "Teething syndrome", category: "K00" },
  { code: "K00.8", description: "Other disorders of tooth development", category: "K00" },
  { code: "K00.9", description: "Disorder of tooth development, unspecified", category: "K00" },
  { code: "K01.0", description: "Embedded teeth", category: "K01" },
  { code: "K01.1", description: "Impacted teeth", category: "K01" },
  { code: "K02.3", description: "Arrested dental caries", category: "K02" },
  { code: "K02.5", description: "Dental caries on pit and fissure surface", category: "K02" },
  { code: "K02.51", description: "Caries pit and fissure surface limited to enamel", category: "K02" },
  { code: "K02.52", description: "Caries pit and fissure surface penetrating into dentin", category: "K02" },
  { code: "K02.53", description: "Caries pit and fissure surface penetrating into pulp", category: "K02" },
  { code: "K02.6", description: "Dental caries on smooth surface", category: "K02" },
  { code: "K02.61", description: "Caries smooth surface limited to enamel", category: "K02" },
  { code: "K02.62", description: "Caries smooth surface penetrating into dentin", category: "K02" },
  { code: "K02.63", description: "Caries smooth surface penetrating into pulp", category: "K02" },
  { code: "K02.7", description: "Dental root caries", category: "K02" },
  { code: "K02.9", description: "Dental caries, unspecified", category: "K02" },
  { code: "K03.0", description: "Excessive attrition of teeth", category: "K03" },
  { code: "K03.1", description: "Abrasion of teeth", category: "K03" },
  { code: "K03.2", description: "Erosion of teeth", category: "K03" },
  { code: "K03.3", description: "Pathological resorption of teeth", category: "K03" },
  { code: "K03.4", description: "Hypercementosis", category: "K03" },
  { code: "K03.5", description: "Ankylosis of teeth", category: "K03" },
  { code: "K03.6", description: "Deposits (accretions) on teeth", category: "K03" },
  { code: "K03.7", description: "Posteruptive color changes of dental hard tissues", category: "K03" },
  { code: "K03.81", description: "Cracked tooth", category: "K03" },
  { code: "K03.89", description: "Other specified diseases of hard tissues of teeth", category: "K03" },
  { code: "K03.9", description: "Disease of hard tissues of teeth, unspecified", category: "K03" },
  { code: "K04.01", description: "Reversible pulpitis", category: "K04" },
  { code: "K04.02", description: "Irreversible pulpitis", category: "K04" },
  { code: "K04.1", description: "Necrosis of pulp", category: "K04" },
  { code: "K04.2", description: "Pulp degeneration", category: "K04" },
  { code: "K04.3", description: "Abnormal hard tissue formation in pulp", category: "K04" },
  { code: "K04.4", description: "Acute apical periodontitis of pulpal origin", category: "K04" },
  { code: "K04.5", description: "Chronic apical periodontitis", category: "K04" },
  { code: "K04.6", description: "Periapical abscess with sinus", category: "K04" },
  { code: "K04.7", description: "Periapical abscess without sinus", category: "K04" },
  { code: "K04.8", description: "Radicular cyst", category: "K04" },
  { code: "K04.90", description: "Unspecified diseases of pulp and periapical tissues", category: "K04" },
  { code: "K04.99", description: "Other diseases of pulp and periapical tissues", category: "K04" },
  { code: "K05.00", description: "Acute gingivitis, plaque induced", category: "K05" },
  { code: "K05.01", description: "Acute gingivitis, non-plaque induced", category: "K05" },
  { code: "K05.10", description: "Chronic gingivitis, plaque induced", category: "K05" },
  { code: "K05.11", description: "Chronic gingivitis, non-plaque induced", category: "K05" },
  { code: "K05.20", description: "Aggressive periodontitis, unspecified", category: "K05" },
  { code: "K05.211", description: "Aggressive periodontitis, localized, slight", category: "K05" },
  { code: "K05.212", description: "Aggressive periodontitis, localized, moderate", category: "K05" },
  { code: "K05.213", description: "Aggressive periodontitis, localized, severe", category: "K05" },
  { code: "K05.219", description: "Aggressive periodontitis, localized, unspecified", category: "K05" },
  { code: "K05.221", description: "Aggressive periodontitis, generalized, slight", category: "K05" },
  { code: "K05.222", description: "Aggressive periodontitis, generalized, moderate", category: "K05" },
  { code: "K05.223", description: "Aggressive periodontitis, generalized, severe", category: "K05" },
  { code: "K05.229", description: "Aggressive periodontitis, generalized, unspecified", category: "K05" },
  { code: "K05.30", description: "Chronic periodontitis, unspecified", category: "K05" },
  { code: "K05.311", description: "Chronic periodontitis, localized, slight", category: "K05" },
  { code: "K05.312", description: "Chronic periodontitis, localized, moderate", category: "K05" },
  { code: "K05.313", description: "Chronic periodontitis, localized, severe", category: "K05" },
  { code: "K05.319", description: "Chronic periodontitis, localized, unspecified", category: "K05" },
  { code: "K05.321", description: "Chronic periodontitis, generalized, slight", category: "K05" },
  { code: "K05.322", description: "Chronic periodontitis, generalized, moderate", category: "K05" },
  { code: "K05.323", description: "Chronic periodontitis, generalized, severe", category: "K05" },
  { code: "K05.329", description: "Chronic periodontitis, generalized, unspecified", category: "K05" },
  { code: "K05.4", description: "Periodontosis", category: "K05" },
  { code: "K05.5", description: "Other periodontal diseases", category: "K05" },
  { code: "K05.6", description: "Periodontal disease, unspecified", category: "K05" },
  { code: "K06.010", description: "Localized gingival recession, unspecified", category: "K06" },
  { code: "K06.011", description: "Localized gingival recession, minimal", category: "K06" },
  { code: "K06.012", description: "Localized gingival recession, moderate", category: "K06" },
  { code: "K06.013", description: "Localized gingival recession, severe", category: "K06" },
  { code: "K06.020", description: "Generalized gingival recession, unspecified", category: "K06" },
  { code: "K06.021", description: "Generalized gingival recession, minimal", category: "K06" },
  { code: "K06.022", description: "Generalized gingival recession, moderate", category: "K06" },
  { code: "K06.023", description: "Generalized gingival recession, severe", category: "K06" },
  { code: "K06.1", description: "Gingival enlargement", category: "K06" },
  { code: "K06.2", description: "Gingival and edentulous alveolar ridge lesions associated with trauma", category: "K06" },
  { code: "K06.3", description: "Horizontal alveolar bone loss", category: "K06" },
  { code: "K06.8", description: "Other specified disorders of gingiva and edentulous alveolar ridge", category: "K06" },
  { code: "K06.9", description: "Disorder of gingiva and edentulous alveolar ridge, unspecified", category: "K06" },
  { code: "K08.0", description: "Exfoliation of teeth due to systemic causes", category: "K08" },
  { code: "K08.101", description: "Complete loss of teeth, unspecified cause, class I", category: "K08" },
  { code: "K08.102", description: "Complete loss of teeth, unspecified cause, class II", category: "K08" },
  { code: "K08.103", description: "Complete loss of teeth, unspecified cause, class III", category: "K08" },
  { code: "K08.104", description: "Complete loss of teeth, unspecified cause, class IV", category: "K08" },
  { code: "K08.109", description: "Complete loss of teeth, unspecified cause, unspecified class", category: "K08" },
  { code: "K08.3", description: "Retained dental root", category: "K08" },
  { code: "K08.50", description: "Unsatisfactory restoration of tooth, unspecified", category: "K08" },
  { code: "K08.51", description: "Open restoration margins of tooth", category: "K08" },
  { code: "K08.52", description: "Unrepairable overhanging of dental restorative materials", category: "K08" },
  { code: "K08.530", description: "Fractured dental restorative material without loss of material", category: "K08" },
  { code: "K08.531", description: "Fractured dental restorative material with loss of material", category: "K08" },
  { code: "K08.539", description: "Fractured dental restorative material, unspecified", category: "K08" },
  { code: "K08.54", description: "Contour of existing restoration of tooth biologically incompatible", category: "K08" },
  { code: "K08.55", description: "Allergy to existing dental restorative material", category: "K08" },
  { code: "K08.56", description: "Poor aesthetic of existing restoration of tooth", category: "K08" },
  { code: "K08.59", description: "Other unsatisfactory restoration of tooth", category: "K08" },
  { code: "K08.81", description: "Primary occlusal trauma", category: "K08" },
  { code: "K08.82", description: "Secondary occlusal trauma", category: "K08" },
  { code: "K08.89", description: "Other specified disorders of teeth and supporting structures", category: "K08" },
  { code: "K08.9", description: "Disorder of teeth and supporting structures, unspecified", category: "K08" },
  { code: "K09.0", description: "Developmental odontogenic cysts", category: "K09" },
  { code: "K09.1", description: "Developmental (nonodontogenic) cysts of oral region", category: "K09" },
  { code: "K09.8", description: "Other cysts of oral region", category: "K09" },
  { code: "K09.9", description: "Cyst of oral region, unspecified", category: "K09" },
  { code: "K11.20", description: "Sialoadenitis, unspecified", category: "K11" },
  { code: "K11.21", description: "Acute sialoadenitis", category: "K11" },
  { code: "K11.22", description: "Acute recurrent sialoadenitis", category: "K11" },
  { code: "K11.23", description: "Chronic sialoadenitis", category: "K11" },
  { code: "K11.3", description: "Abscess of salivary gland", category: "K11" },
  { code: "K11.4", description: "Fistula of salivary gland", category: "K11" },
  { code: "K11.5", description: "Sialolithiasis", category: "K11" },
  { code: "K11.6", description: "Mucocele of salivary gland", category: "K11" },
  { code: "K11.7", description: "Disturbances of salivary secretion", category: "K11" },
  { code: "K11.8", description: "Other diseases of salivary glands", category: "K11" },
  { code: "K11.9", description: "Disease of salivary gland, unspecified", category: "K11" },
  { code: "K12.0", description: "Recurrent oral aphthae", category: "K12" },
  { code: "K12.1", description: "Other forms of stomatitis", category: "K12" },
  { code: "K12.2", description: "Cellulitis and abscess of mouth", category: "K12" },
  { code: "K12.30", description: "Oral mucositis (ulcerative), unspecified", category: "K12" },
  { code: "K12.31", description: "Oral mucositis (ulcerative) due to antineoplastic therapy", category: "K12" },
  { code: "K12.32", description: "Oral mucositis (ulcerative) due to other drugs", category: "K12" },
  { code: "K12.33", description: "Oral mucositis (ulcerative) due to radiation", category: "K12" },
  { code: "K12.39", description: "Other oral mucositis (ulcerative)", category: "K12" },
  { code: "K13.0", description: "Diseases of lips", category: "K13" },
  { code: "K13.1", description: "Cheek and lip biting", category: "K13" },
  { code: "K13.21", description: "Leukoplakia of oral mucosa, including tongue", category: "K13" },
  { code: "K13.22", description: "Minimal keratinized residual ridge mucosa", category: "K13" },
  { code: "K13.23", description: "Excessive keratinized residual ridge mucosa", category: "K13" },
  { code: "K13.24", description: "Leukokeratosis nicotina palati", category: "K13" },
  { code: "K13.29", description: "Other disturbances of oral epithelium, including tongue", category: "K13" },
  { code: "K13.3", description: "Hairy leukoplakia", category: "K13" },
  { code: "K13.4", description: "Granuloma and granuloma-like lesions of oral mucosa", category: "K13" },
  { code: "K13.5", description: "Oral submucous fibrosis", category: "K13" },
  { code: "K13.6", description: "Irritative hyperplasia of oral mucosa", category: "K13" },
  { code: "K13.70", description: "Unspecified lesions of oral mucosa", category: "K13" },
  { code: "K13.79", description: "Other lesions of oral mucosa", category: "K13" },
  { code: "K14.0", description: "Glossitis", category: "K14" },
  { code: "K14.1", description: "Geographic tongue", category: "K14" },
  { code: "K14.2", description: "Median rhomboid glossitis", category: "K14" },
  { code: "K14.3", description: "Hypertrophy of tongue papillae", category: "K14" },
  { code: "K14.4", description: "Atrophy of tongue papillae", category: "K14" },
  { code: "K14.5", description: "Plicated tongue", category: "K14" },
  { code: "K14.6", description: "Glossodynia", category: "K14" },
  { code: "K14.8", description: "Other diseases of tongue", category: "K14" },
  { code: "K14.9", description: "Disease of tongue, unspecified", category: "K14" }
]

icd_codes.each do |icd|
  IcdCode.find_or_create_by!(code: icd[:code]) do |i|
    i.description = icd[:description]
    i.category = icd[:category]
  end
end
